// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package datalink

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataLinkClient is the client API for DataLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataLinkClient interface {
	Handshake(ctx context.Context, opts ...grpc.CallOption) (DataLink_HandshakeClient, error)
	Replicate(ctx context.Context, opts ...grpc.CallOption) (DataLink_ReplicateClient, error)
}

type dataLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewDataLinkClient(cc grpc.ClientConnInterface) DataLinkClient {
	return &dataLinkClient{cc}
}

func (c *dataLinkClient) Handshake(ctx context.Context, opts ...grpc.CallOption) (DataLink_HandshakeClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataLink_ServiceDesc.Streams[0], "/datalink.DataLink/Handshake", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataLinkHandshakeClient{stream}
	return x, nil
}

type DataLink_HandshakeClient interface {
	Send(*ClientHandshakeMsg) error
	Recv() (*ServerHandshakeMsg, error)
	grpc.ClientStream
}

type dataLinkHandshakeClient struct {
	grpc.ClientStream
}

func (x *dataLinkHandshakeClient) Send(m *ClientHandshakeMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataLinkHandshakeClient) Recv() (*ServerHandshakeMsg, error) {
	m := new(ServerHandshakeMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataLinkClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (DataLink_ReplicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataLink_ServiceDesc.Streams[1], "/datalink.DataLink/Replicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataLinkReplicateClient{stream}
	return x, nil
}

type DataLink_ReplicateClient interface {
	Send(*Message) error
	Recv() (*Confirmation, error)
	grpc.ClientStream
}

type dataLinkReplicateClient struct {
	grpc.ClientStream
}

func (x *dataLinkReplicateClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataLinkReplicateClient) Recv() (*Confirmation, error) {
	m := new(Confirmation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataLinkServer is the server API for DataLink service.
// All implementations must embed UnimplementedDataLinkServer
// for forward compatibility
type DataLinkServer interface {
	Handshake(DataLink_HandshakeServer) error
	Replicate(DataLink_ReplicateServer) error
	mustEmbedUnimplementedDataLinkServer()
}

// UnimplementedDataLinkServer must be embedded to have forward compatible implementations.
type UnimplementedDataLinkServer struct {
}

func (UnimplementedDataLinkServer) Handshake(DataLink_HandshakeServer) error {
	return status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedDataLinkServer) Replicate(DataLink_ReplicateServer) error {
	return status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedDataLinkServer) mustEmbedUnimplementedDataLinkServer() {}

// UnsafeDataLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataLinkServer will
// result in compilation errors.
type UnsafeDataLinkServer interface {
	mustEmbedUnimplementedDataLinkServer()
}

func RegisterDataLinkServer(s grpc.ServiceRegistrar, srv DataLinkServer) {
	s.RegisterService(&DataLink_ServiceDesc, srv)
}

func _DataLink_Handshake_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataLinkServer).Handshake(&dataLinkHandshakeServer{stream})
}

type DataLink_HandshakeServer interface {
	Send(*ServerHandshakeMsg) error
	Recv() (*ClientHandshakeMsg, error)
	grpc.ServerStream
}

type dataLinkHandshakeServer struct {
	grpc.ServerStream
}

func (x *dataLinkHandshakeServer) Send(m *ServerHandshakeMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataLinkHandshakeServer) Recv() (*ClientHandshakeMsg, error) {
	m := new(ClientHandshakeMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DataLink_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataLinkServer).Replicate(&dataLinkReplicateServer{stream})
}

type DataLink_ReplicateServer interface {
	Send(*Confirmation) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type dataLinkReplicateServer struct {
	grpc.ServerStream
}

func (x *dataLinkReplicateServer) Send(m *Confirmation) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataLinkReplicateServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataLink_ServiceDesc is the grpc.ServiceDesc for DataLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datalink.DataLink",
	HandlerType: (*DataLinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Handshake",
			Handler:       _DataLink_Handshake_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Replicate",
			Handler:       _DataLink_Replicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "datalink.proto",
}
