// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: datalink.proto

package datalink

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	razpravljalnica "seminarska/proto/razpravljalnica"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_Create Operation = 0
	Operation_Update Operation = 1
	Operation_Delete Operation = 2
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "Create",
		1: "Update",
		2: "Delete",
	}
	Operation_value = map[string]int32{
		"Create": 0,
		"Update": 1,
		"Delete": 2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_datalink_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_datalink_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageIndex int32     `protobuf:"varint,1,opt,name=message_index,json=messageIndex,proto3" json:"message_index,omitempty"`
	RequestId    string    `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // used to identify the message independently of its index (which is not immediately known)
	Op           Operation `protobuf:"varint,3,opt,name=op,proto3,enum=datalink.Operation" json:"op,omitempty"`
	// Types that are assignable to Payload:
	//	*Message_User
	//	*Message_Topic
	//	*Message_Message
	//	*Message_Like
	Payload isMessage_Payload `protobuf_oneof:"payload"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datalink_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_datalink_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageIndex() int32 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

func (x *Message) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Message) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_Create
}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Message) GetUser() *razpravljalnica.User {
	if x, ok := x.GetPayload().(*Message_User); ok {
		return x.User
	}
	return nil
}

func (x *Message) GetTopic() *razpravljalnica.Topic {
	if x, ok := x.GetPayload().(*Message_Topic); ok {
		return x.Topic
	}
	return nil
}

func (x *Message) GetMessage() *razpravljalnica.Message {
	if x, ok := x.GetPayload().(*Message_Message); ok {
		return x.Message
	}
	return nil
}

func (x *Message) GetLike() *razpravljalnica.Like {
	if x, ok := x.GetPayload().(*Message_Like); ok {
		return x.Like
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_User struct {
	User *razpravljalnica.User `protobuf:"bytes,4,opt,name=user,proto3,oneof"`
}

type Message_Topic struct {
	Topic *razpravljalnica.Topic `protobuf:"bytes,5,opt,name=topic,proto3,oneof"`
}

type Message_Message struct {
	Message *razpravljalnica.Message `protobuf:"bytes,6,opt,name=message,proto3,oneof"`
}

type Message_Like struct {
	Like *razpravljalnica.Like `protobuf:"bytes,7,opt,name=like,proto3,oneof"`
}

func (*Message_User) isMessage_Payload() {}

func (*Message_Topic) isMessage_Payload() {}

func (*Message_Message) isMessage_Payload() {}

func (*Message_Like) isMessage_Payload() {}

type Confirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageIndex int32  `protobuf:"varint,1,opt,name=message_index,json=messageIndex,proto3" json:"message_index,omitempty"`
	RequestId    string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ok           bool   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error        string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datalink_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_datalink_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{1}
}

func (x *Confirmation) GetMessageIndex() int32 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

func (x *Confirmation) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Confirmation) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Confirmation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClientHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastConfIndex int32 `protobuf:"varint,1,opt,name=last_conf_index,json=lastConfIndex,proto3" json:"last_conf_index,omitempty"`
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datalink_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_datalink_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetLastConfIndex() int32 {
	if x != nil {
		return x.LastConfIndex
	}
	return 0
}

type ClientSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *ClientSync) Reset() {
	*x = ClientSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datalink_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSync) ProtoMessage() {}

func (x *ClientSync) ProtoReflect() protoreflect.Message {
	mi := &file_datalink_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSync.ProtoReflect.Descriptor instead.
func (*ClientSync) Descriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{3}
}

func (x *ClientSync) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DatabaseSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpCount         int32                      `protobuf:"varint,1,opt,name=op_count,json=opCount,proto3" json:"op_count,omitempty"`
	Users           []*razpravljalnica.User    `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Topics          []*razpravljalnica.Topic   `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	Messages        []*razpravljalnica.Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	Likes           []*razpravljalnica.Like    `protobuf:"bytes,5,rep,name=likes,proto3" json:"likes,omitempty"`
	PendingRequests []*Message                 `protobuf:"bytes,6,rep,name=pending_requests,json=pendingRequests,proto3" json:"pending_requests,omitempty"`
}

func (x *DatabaseSnapshot) Reset() {
	*x = DatabaseSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datalink_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatabaseSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseSnapshot) ProtoMessage() {}

func (x *DatabaseSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_datalink_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseSnapshot.ProtoReflect.Descriptor instead.
func (*DatabaseSnapshot) Descriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{4}
}

func (x *DatabaseSnapshot) GetOpCount() int32 {
	if x != nil {
		return x.OpCount
	}
	return 0
}

func (x *DatabaseSnapshot) GetUsers() []*razpravljalnica.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *DatabaseSnapshot) GetTopics() []*razpravljalnica.Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *DatabaseSnapshot) GetMessages() []*razpravljalnica.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *DatabaseSnapshot) GetLikes() []*razpravljalnica.Like {
	if x != nil {
		return x.Likes
	}
	return nil
}

func (x *DatabaseSnapshot) GetPendingRequests() []*Message {
	if x != nil {
		return x.PendingRequests
	}
	return nil
}

type ServerHelo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastMsgIndex    int32 `protobuf:"varint,1,opt,name=last_msg_index,json=lastMsgIndex,proto3" json:"last_msg_index,omitempty"`
	RequestTransfer bool  `protobuf:"varint,2,opt,name=request_transfer,json=requestTransfer,proto3" json:"request_transfer,omitempty"`
}

func (x *ServerHelo) Reset() {
	*x = ServerHelo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datalink_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerHelo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHelo) ProtoMessage() {}

func (x *ServerHelo) ProtoReflect() protoreflect.Message {
	mi := &file_datalink_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHelo.ProtoReflect.Descriptor instead.
func (*ServerHelo) Descriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{5}
}

func (x *ServerHelo) GetLastMsgIndex() int32 {
	if x != nil {
		return x.LastMsgIndex
	}
	return 0
}

func (x *ServerHelo) GetRequestTransfer() bool {
	if x != nil {
		return x.RequestTransfer
	}
	return false
}

type ServerSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confirmations []*Confirmation `protobuf:"bytes,1,rep,name=confirmations,proto3" json:"confirmations,omitempty"`
}

func (x *ServerSync) Reset() {
	*x = ServerSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datalink_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSync) ProtoMessage() {}

func (x *ServerSync) ProtoReflect() protoreflect.Message {
	mi := &file_datalink_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSync.ProtoReflect.Descriptor instead.
func (*ServerSync) Descriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{6}
}

func (x *ServerSync) GetConfirmations() []*Confirmation {
	if x != nil {
		return x.Confirmations
	}
	return nil
}

type ClientHandshakeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*ClientHandshakeMsg_Hello
	//	*ClientHandshakeMsg_Sync
	//	*ClientHandshakeMsg_Db
	Payload isClientHandshakeMsg_Payload `protobuf_oneof:"payload"`
}

func (x *ClientHandshakeMsg) Reset() {
	*x = ClientHandshakeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datalink_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientHandshakeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHandshakeMsg) ProtoMessage() {}

func (x *ClientHandshakeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_datalink_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHandshakeMsg.ProtoReflect.Descriptor instead.
func (*ClientHandshakeMsg) Descriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{7}
}

func (m *ClientHandshakeMsg) GetPayload() isClientHandshakeMsg_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ClientHandshakeMsg) GetHello() *ClientHello {
	if x, ok := x.GetPayload().(*ClientHandshakeMsg_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *ClientHandshakeMsg) GetSync() *ClientSync {
	if x, ok := x.GetPayload().(*ClientHandshakeMsg_Sync); ok {
		return x.Sync
	}
	return nil
}

func (x *ClientHandshakeMsg) GetDb() *DatabaseSnapshot {
	if x, ok := x.GetPayload().(*ClientHandshakeMsg_Db); ok {
		return x.Db
	}
	return nil
}

type isClientHandshakeMsg_Payload interface {
	isClientHandshakeMsg_Payload()
}

type ClientHandshakeMsg_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientHandshakeMsg_Sync struct {
	Sync *ClientSync `protobuf:"bytes,2,opt,name=sync,proto3,oneof"`
}

type ClientHandshakeMsg_Db struct {
	Db *DatabaseSnapshot `protobuf:"bytes,3,opt,name=db,proto3,oneof"`
}

func (*ClientHandshakeMsg_Hello) isClientHandshakeMsg_Payload() {}

func (*ClientHandshakeMsg_Sync) isClientHandshakeMsg_Payload() {}

func (*ClientHandshakeMsg_Db) isClientHandshakeMsg_Payload() {}

type ServerHandshakeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*ServerHandshakeMsg_Hello
	//	*ServerHandshakeMsg_Sync
	Payload isServerHandshakeMsg_Payload `protobuf_oneof:"payload"`
}

func (x *ServerHandshakeMsg) Reset() {
	*x = ServerHandshakeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datalink_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerHandshakeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHandshakeMsg) ProtoMessage() {}

func (x *ServerHandshakeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_datalink_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHandshakeMsg.ProtoReflect.Descriptor instead.
func (*ServerHandshakeMsg) Descriptor() ([]byte, []int) {
	return file_datalink_proto_rawDescGZIP(), []int{8}
}

func (m *ServerHandshakeMsg) GetPayload() isServerHandshakeMsg_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ServerHandshakeMsg) GetHello() *ServerHelo {
	if x, ok := x.GetPayload().(*ServerHandshakeMsg_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *ServerHandshakeMsg) GetSync() *ServerSync {
	if x, ok := x.GetPayload().(*ServerHandshakeMsg_Sync); ok {
		return x.Sync
	}
	return nil
}

type isServerHandshakeMsg_Payload interface {
	isServerHandshakeMsg_Payload()
}

type ServerHandshakeMsg_Hello struct {
	Hello *ServerHelo `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ServerHandshakeMsg_Sync struct {
	Sync *ServerSync `protobuf:"bytes,2,opt,name=sync,proto3,oneof"`
}

func (*ServerHandshakeMsg_Hello) isServerHandshakeMsg_Payload() {}

func (*ServerHandshakeMsg_Sync) isServerHandshakeMsg_Payload() {}

var File_datalink_proto protoreflect.FileDescriptor

var file_datalink_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e, 0x6b, 0x1a, 0x15, 0x72, 0x61, 0x7a, 0x70,
	0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbd, 0x02, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x2b, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a,
	0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c,
	0x6e, 0x69, 0x63, 0x61, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x48, 0x00, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a,
	0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6c, 0x69, 0x6b,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61,
	0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x48, 0x00,
	0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x78, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x0b, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x3b, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x6e, 0x63,
	0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22,
	0xab, 0x02, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x2b, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x06,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72,
	0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x34, 0x0a, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e,
	0x69, 0x63, 0x61, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x12,
	0x3c, 0x0a, 0x10, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0f, 0x70, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x5d, 0x0a,
	0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x65, 0x6c, 0x6f, 0x12, 0x24, 0x0a, 0x0e, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0x4a, 0x0a, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x3c, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xa8, 0x01, 0x0a, 0x12, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x4d, 0x73, 0x67, 0x12,
	0x2d, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x2a,
	0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x79,
	0x6e, 0x63, 0x48, 0x00, 0x52, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x12, 0x2c, 0x0a, 0x02, 0x64, 0x62,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e,
	0x6b, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x48, 0x00, 0x52, 0x02, 0x64, 0x62, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x79, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x61, 0x6e,
	0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x2c, 0x0a, 0x05, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6c,
	0x69, 0x6e, 0x6b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x65, 0x6c, 0x6f, 0x48, 0x00,
	0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x2a, 0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e, 0x6b,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x48, 0x00, 0x52, 0x04, 0x73,
	0x79, 0x6e, 0x63, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x2f,
	0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x02, 0x32,
	0x93, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x4b, 0x0a, 0x09,
	0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x1c, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0x1c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69,
	0x6e, 0x6b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61,
	0x6b, 0x65, 0x4d, 0x73, 0x67, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x09, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e,
	0x6b, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x16, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x28, 0x01, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x73, 0x65, 0x6d, 0x69, 0x6e, 0x61, 0x72,
	0x73, 0x6b, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69,
	0x6e, 0x6b, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_datalink_proto_rawDescOnce sync.Once
	file_datalink_proto_rawDescData = file_datalink_proto_rawDesc
)

func file_datalink_proto_rawDescGZIP() []byte {
	file_datalink_proto_rawDescOnce.Do(func() {
		file_datalink_proto_rawDescData = protoimpl.X.CompressGZIP(file_datalink_proto_rawDescData)
	})
	return file_datalink_proto_rawDescData
}

var file_datalink_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_datalink_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_datalink_proto_goTypes = []interface{}{
	(Operation)(0),                  // 0: datalink.Operation
	(*Message)(nil),                 // 1: datalink.Message
	(*Confirmation)(nil),            // 2: datalink.Confirmation
	(*ClientHello)(nil),             // 3: datalink.ClientHello
	(*ClientSync)(nil),              // 4: datalink.ClientSync
	(*DatabaseSnapshot)(nil),        // 5: datalink.DatabaseSnapshot
	(*ServerHelo)(nil),              // 6: datalink.ServerHelo
	(*ServerSync)(nil),              // 7: datalink.ServerSync
	(*ClientHandshakeMsg)(nil),      // 8: datalink.ClientHandshakeMsg
	(*ServerHandshakeMsg)(nil),      // 9: datalink.ServerHandshakeMsg
	(*razpravljalnica.User)(nil),    // 10: razpravljalnica.User
	(*razpravljalnica.Topic)(nil),   // 11: razpravljalnica.Topic
	(*razpravljalnica.Message)(nil), // 12: razpravljalnica.Message
	(*razpravljalnica.Like)(nil),    // 13: razpravljalnica.Like
}
var file_datalink_proto_depIdxs = []int32{
	0,  // 0: datalink.Message.op:type_name -> datalink.Operation
	10, // 1: datalink.Message.user:type_name -> razpravljalnica.User
	11, // 2: datalink.Message.topic:type_name -> razpravljalnica.Topic
	12, // 3: datalink.Message.message:type_name -> razpravljalnica.Message
	13, // 4: datalink.Message.like:type_name -> razpravljalnica.Like
	1,  // 5: datalink.ClientSync.messages:type_name -> datalink.Message
	10, // 6: datalink.DatabaseSnapshot.users:type_name -> razpravljalnica.User
	11, // 7: datalink.DatabaseSnapshot.topics:type_name -> razpravljalnica.Topic
	12, // 8: datalink.DatabaseSnapshot.messages:type_name -> razpravljalnica.Message
	13, // 9: datalink.DatabaseSnapshot.likes:type_name -> razpravljalnica.Like
	1,  // 10: datalink.DatabaseSnapshot.pending_requests:type_name -> datalink.Message
	2,  // 11: datalink.ServerSync.confirmations:type_name -> datalink.Confirmation
	3,  // 12: datalink.ClientHandshakeMsg.hello:type_name -> datalink.ClientHello
	4,  // 13: datalink.ClientHandshakeMsg.sync:type_name -> datalink.ClientSync
	5,  // 14: datalink.ClientHandshakeMsg.db:type_name -> datalink.DatabaseSnapshot
	6,  // 15: datalink.ServerHandshakeMsg.hello:type_name -> datalink.ServerHelo
	7,  // 16: datalink.ServerHandshakeMsg.sync:type_name -> datalink.ServerSync
	8,  // 17: datalink.DataLink.Handshake:input_type -> datalink.ClientHandshakeMsg
	1,  // 18: datalink.DataLink.Replicate:input_type -> datalink.Message
	9,  // 19: datalink.DataLink.Handshake:output_type -> datalink.ServerHandshakeMsg
	2,  // 20: datalink.DataLink.Replicate:output_type -> datalink.Confirmation
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_datalink_proto_init() }
func file_datalink_proto_init() {
	if File_datalink_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datalink_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datalink_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datalink_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datalink_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datalink_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatabaseSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datalink_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerHelo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datalink_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datalink_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientHandshakeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datalink_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerHandshakeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_datalink_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_User)(nil),
		(*Message_Topic)(nil),
		(*Message_Message)(nil),
		(*Message_Like)(nil),
	}
	file_datalink_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*ClientHandshakeMsg_Hello)(nil),
		(*ClientHandshakeMsg_Sync)(nil),
		(*ClientHandshakeMsg_Db)(nil),
	}
	file_datalink_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ServerHandshakeMsg_Hello)(nil),
		(*ServerHandshakeMsg_Sync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datalink_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datalink_proto_goTypes,
		DependencyIndexes: file_datalink_proto_depIdxs,
		EnumInfos:         file_datalink_proto_enumTypes,
		MessageInfos:      file_datalink_proto_msgTypes,
	}.Build()
	File_datalink_proto = out.File
	file_datalink_proto_rawDesc = nil
	file_datalink_proto_goTypes = nil
	file_datalink_proto_depIdxs = nil
}
