// Code generated by "stringer -type=event"; DO NOT EDIT.

package chain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PredecessorConnect-0]
	_ = x[SuccessorConnect-1]
	_ = x[PredecessorDisconnect-2]
	_ = x[SuccessorDisconnect-3]
	_ = x[RoleRelay-4]
	_ = x[RoleReader-5]
	_ = x[RoleConfirmer-6]
	_ = x[RoleReaderConfirmer-7]
}

const _event_name = "PredecessorConnectSuccessorConnectPredecessorDisconnectSuccessorDisconnectRoleRelayRoleReaderRoleConfirmerRoleReaderConfirmer"

var _event_index = [...]uint8{0, 18, 34, 55, 74, 83, 93, 106, 125}

func (i event) String() string {
	if i < 0 || i >= event(len(_event_index)-1) {
		return "event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _event_name[_event_index[i]:_event_index[i+1]]
}
