// Code generated by "stringer -type=Role"; DO NOT EDIT.

package chain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Relay-0]
	_ = x[Reader-1]
	_ = x[Confirmer-2]
	_ = x[ReaderConfirmer-3]
}

const _Role_name = "RelayReaderConfirmerReaderConfirmer"

var _Role_index = [...]uint8{0, 5, 11, 20, 35}

func (i Role) String() string {
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
